version: '3.8'

services:
  yolo-api:
    build: .
    container_name: yolo-inference-platform
    ports:
      - "5000:5000"
    volumes:
      # Persist models, uploads, and results
      - ./data/models:/app/models
      - ./data/uploads:/app/uploads
      - ./data/results:/app/results
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  models:
  uploads:
  results:
